server:
  port: 8080

spring:

  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/tasks"
    username: psql
    password: psql

  liquibase:
    enabled: true
    url: "jdbc:postgresql://localhost:5432/tasks"
    user: psql
    password: psql
    change-log: "classpath:liquibase/changelog.yml"

jms:
  url: "tcp://localhost:61616"
  user: "input"
  password: "input"
  concurrency: "1-1"

application:
  name: "TASKSSERVICE"

# todo - move with journaling
journaling:
  enable: true
