version: '3.5'

services:
  psql:
    container_name: tasks-postgress
    image: postgres:13.6-alpine
    restart: no
    volumes:
      - ./start-db-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: psql
    ports:
      - "5432:5432"
