-- liquibase formatted sql
-- changeset tiunchik:1
create table task (
    id integer primary key generated by default as identity,
    name varchar(100) not null,
    description text not null
);
-- rollback drop table task;
