-- liquibase formatted sql
-- changeset tiunchik:2
create table task_user_relations
(
    id      integer primary key generated by default as identity,
    task_id integer not null,
    user_id integer not null
);
-- rollback drop table task_user_relations;
